export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const FETCH_ALL = 'FETCH_ALL'
export const LIKE = 'LIKE'

export const getAllPosts = 'getPosts'
export const createSinglePost = 'createPost'
export const updateSinglePost = 'updatePost'
export const deleteSinglePost = 'deletePost'
export const likeSinglePost = 'likePost'