export const getAllPosts = '/getPosts'
export const createSinglePost = '/createPost'
export const updateSinglePost = '/updatePost/:id'
export const deleteSinglePost = '/deletePost/:id'
export const likeSinglePost = '/likePost/:id'